### ISSUE TITLE
Examples generator compilation error

### ISSUE THREAD

**Issue by patatoid** [fuelen/ecto_erd#1]
Thanks for the package, it helps a lot creating beautiful ERD diagrams, I was missing those these days :)

Using `ecto_erd` as a dependency has raised a compilation error in my setup.
```
Error while loading project :ecto_erd at /home/pascal/elixir/realworld/elixir-phoenix-realworld-example-app/deps/ecto_erd
** (Code.LoadError) could not load /home/pascal/elixir/realworld/elixir-phoenix-realworld-example-app/deps/ecto_erd/examples_generator.exs
    (elixir 1.12.1) lib/code.ex:1806: Code.find_file/2
    (elixir 1.12.1) lib/code.ex:1502: Code.compile_file/2
    /home/pascal/elixir/realworld/elixir-phoenix-realworld-example-app/deps/ecto_erd/mix.exs:1: (file)
    (elixir 1.12.1) lib/code.ex:1502: Code.compile_file/2
```
It appears that `ExampleGenerator` is not available for compilation [here](https://github.com/fuelen/ecto_erd/blob/main/mix.exs#L1).

Maybe a workaround would be to compile the file at runtime while generating the docs as the module is needed only for documentation generation.

**Comment by fuelen** [comment]
Hey @patatoid 

Thanks for pointing out. Fixed in https://github.com/fuelen/ecto_erd/commit/2ee76567056f5cc71e040846eb641c81e3e362e1
